package ch.sbb.polarion.extension.pdf_exporter.util;

import com.polarion.core.util.logging.Logger;
import lombok.experimental.UtilityClass;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.cos.COSDictionary;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.common.PDMetadata;
import org.jetbrains.annotations.NotNull;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Calendar;

/**
 * Utility class for processing PDF/A-4 documents to ensure compliance with ISO 19005-4:2020 specification.
 * <p>
 * This processor fixes common compliance issues that may be present in PDF/A-4 documents generated by WeasyPrint:
 * <ul>
 *     <li>Removes non-compliant entries from document information dictionary (keeping only ModDate)</li>
 *     <li>Removes the Info key from trailer dictionary when no PieceInfo exists in document catalog</li>
 *     <li>Fixes XMP metadata to use correct pdfaid:rev format (four-digit year instead of revision number)</li>
 *     <li>Removes pdfaid:conformance from XMP metadata (not allowed for PDF/A-4b and PDF/A-4u)</li>
 * </ul>
 */
@UtilityClass
public class PdfA4Processor {
    private static final Logger logger = Logger.getLogger(PdfA4Processor.class);

    /**
     * Processes a PDF/A-4 document to fix compliance issues according to ISO 19005-4:2020.
     *
     * @param pdfBytes the original PDF content
     * @return the processed PDF content with compliance fixes applied
     * @throws IOException if an error occurs during PDF processing
     */
    public byte[] processPdfA4(byte[] pdfBytes) throws IOException {
        try (PDDocument document = Loader.loadPDF(pdfBytes);
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            // Fix document information dictionary
            fixDocumentInformation(document);

            // Fix XMP metadata
            fixXmpMetadata(document);

            // Save the modified document
            document.save(outputStream);
            return outputStream.toByteArray();
        }
    }

    /**
     * Fixes the document information dictionary according to PDF/A-4 requirements.
     * <p>
     * According to ISO 19005-4:2020 clause 6.1.3:
     * <ul>
     *     <li>The Info key shall not be present in the trailer dictionary unless there exists a PieceInfo entry</li>
     *     <li>If a document information dictionary is present, it shall only contain a ModDate entry</li>
     * </ul>
     *
     * @param document the PDF document to process
     */
    private void fixDocumentInformation(@NotNull PDDocument document) {
        PDDocumentInformation info = document.getDocumentInformation();
        COSDictionary catalog = document.getDocumentCatalog().getCOSObject();

        // Check if PieceInfo exists in the document catalog
        boolean hasPieceInfo = catalog.containsKey(COSName.PIECE_INFO);

        if (!hasPieceInfo) {
            // If no PieceInfo exists, we should remove the Info dictionary entirely
            COSDictionary trailer = document.getDocument().getTrailer();
            trailer.removeItem(COSName.INFO);
            logger.debug("Removed Info key from trailer dictionary (no PieceInfo present)");
        } else if (info != null) {
            // If PieceInfo exists and Info is present, keep only ModDate
            Calendar modDate = info.getModificationDate();

            // Clear all information
            COSDictionary infoDictionary = info.getCOSObject();
            infoDictionary.clear();

            // Restore only ModDate if it was present
            if (modDate != null) {
                info.setModificationDate(modDate);
                logger.debug("Cleaned document information dictionary, keeping only ModDate");
            } else {
                // If no ModDate exists, set it to current time
                info.setModificationDate(Calendar.getInstance());
                logger.debug("Set ModDate to current time in document information dictionary");
            }
        }
    }

    /**
     * Fixes XMP metadata according to PDF/A-4 requirements.
     * <p>
     * According to ISO 19005-4:2020 clause 6.7.3:
     * <ul>
     *     <li>The value of "pdfaid:rev" shall be the four-digit year (e.g., "2020" not "4")</li>
     *     <li>Files not conforming to PDF/A-4e or PDF/A-4f shall not provide "pdfaid:conformance"</li>
     * </ul>
     *
     * @param document the PDF document to process
     */
    private void fixXmpMetadata(@NotNull PDDocument document) throws IOException {
        PDMetadata metadata = document.getDocumentCatalog().getMetadata();
        if (metadata == null) {
            logger.warn("No XMP metadata found in document");
            return;
        }

        // Read current metadata as string
        String metadataString = new String(metadata.toByteArray(), StandardCharsets.UTF_8);
        String originalMetadata = metadataString;

        // Check if this is PDF/A-4
        boolean isPdfA4 = metadataString.contains("pdfaid:part=\"4\"") ||
                          metadataString.contains("pdfaid:part='4'") ||
                          metadataString.contains("pdfaid:part>4<");

        if (!isPdfA4) {
            logger.debug("Not PDF/A-4, skipping metadata fixes");
            return;
        }

        String fixedMetadata = metadataString;

        // Fix 1: Add pdfaid:rev="2020" if missing or fix if present
        // WeasyPrint doesn't add pdfaid:rev for PDF/A-4, but it's required by ISO 19005-4:2020
        if (metadataString.contains("pdfaid:rev")) {
            // Replace existing rev value with year
            fixedMetadata = fixedMetadata.replaceAll(
                    "(pdfaid:rev=['\"])\\d{1,4}(['\"])",
                    "$12020$2"
            );
            logger.debug("Updated existing pdfaid:rev to 2020");
        } else {
            // Add pdfaid:rev="2020" to the rdf:Description element that has pdfaid:part
            fixedMetadata = fixedMetadata.replaceAll(
                    "(<rdf:Description[^>]*pdfaid:part=\"4\")",
                    "$1 pdfaid:rev=\"2020\""
            );
            fixedMetadata = fixedMetadata.replaceAll(
                    "(<rdf:Description[^>]*pdfaid:part='4')",
                    "$1 pdfaid:rev=\"2020\""
            );
            logger.debug("Added pdfaid:rev=\"2020\" to XMP metadata");
        }

        // Fix 2: Remove pdfaid:conformance for PDF/A-4b and PDF/A-4u
        // These variants should not have conformance level (only PDF/A-4e and PDF/A-4f use it)
        if (metadataString.contains("pdfaid:conformance")) {
            // Remove conformance in attribute form (both single and double quotes)
            fixedMetadata = fixedMetadata.replaceAll(
                    "\\s+pdfaid:conformance=['\"][^'\"]*['\"]",
                    ""
            );
            logger.debug("Removed pdfaid:conformance from XMP metadata");
        }

        if (!fixedMetadata.equals(originalMetadata)) {
            // Update metadata with fixed version
            metadata.importXMPMetadata(fixedMetadata.getBytes(StandardCharsets.UTF_8));
            logger.info("Updated XMP metadata for PDF/A-4 compliance");
        } else {
            logger.debug("No XMP metadata changes needed");
        }
    }
}
