package ch.sbb.polarion.extension.pdf_exporter.util;

import com.polarion.core.util.logging.Logger;
import lombok.experimental.UtilityClass;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.cos.COSArray;
import org.apache.pdfbox.cos.COSBase;
import org.apache.pdfbox.cos.COSDictionary;
import org.apache.pdfbox.cos.COSName;
import org.apache.pdfbox.cos.COSObject;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.common.PDMetadata;
import org.apache.pdfbox.pdmodel.documentinterchange.logicalstructure.PDStructureElement;
import org.apache.pdfbox.pdmodel.documentinterchange.logicalstructure.PDStructureTreeRoot;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.VisibleForTesting;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Utility class for processing PDF/UA-2 documents to ensure compliance with ISO 14289-2:2024 specification.
 * <p>
 * This processor fixes common compliance issues that may be present in PDF/UA-2 documents generated by WeasyPrint
 * or after PDF merging operations:
 * <ul>
 *     <li>Fixes XMP metadata to use correct pdfuaid:rev format (four-digit year "2024" instead of revision number)</li>
 *     <li>Gives the Document element under the structure tree root the PDF 2.0 namespace, which a merge drops: PDFBox
 *         wraps the Document elements of the merged files, which keep it, in a Document of its own without one
 *         (ISO 14289-2:2024, 8.2.5.2)</li>
 *     <li>Writes the document as PDF 2.0 again, which a merge writes as 1.6</li>
 * </ul>
 * The rest of the structure PDF/UA-2 requires, WeasyPrint writes since the WeasyPrint service 70.0.2.
 */
@UtilityClass
public class PdfUa2Processor {
    private static final Logger logger = Logger.getLogger(PdfUa2Processor.class);
    private static final String PDF_UA_2_REV_YEAR = "2024";
    private static final String PDFUAID_REV = "pdfuaid:rev";
    private static final String PDFUAID_PART = "pdfuaid:part";
    private static final String STRUCTURE_TYPE_DOCUMENT = "Document";
    private static final String PDF_2_NAMESPACE = "http://iso.org/pdf2/ssn";
    private static final COSName NS = COSName.getPDFName("NS");
    private static final COSName NAMESPACES = COSName.getPDFName("Namespaces");

    /**
     * Processes a PDF/UA-2 document to fix compliance issues according to ISO 14289-2:2024.
     * <p>
     * Currently only fixes the pdfuaid:rev metadata value to "2024".
     *
     * @param pdfBytes the original PDF content
     * @return the processed PDF content with compliance fixes applied
     * @throws IOException if an error occurs during PDF processing
     */
    public byte[] processPdfUa2(byte[] pdfBytes) throws IOException {
        try (PDDocument document = Loader.loadPDF(pdfBytes);
             ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {

            // Fix XMP metadata
            fixXmpMetadata(document);

            // Give the Document element its namespace, and the document its version, which a merge drops
            fixStructureNamespace(document);
            document.setVersion(2.0f);
            document.getDocumentCatalog().getCOSObject().setItem(COSName.VERSION, COSName.getPDFName("2.0"));

            // Save the modified document
            document.save(outputStream);
            return PdfA4Processor.fixPdfHeader(outputStream.toByteArray());
        }
    }

    /**
     * Gives each Document element under the structure tree root the PDF 2.0 namespace, and lists that namespace in the
     * root. It takes the namespace of the elements below where one has it, as the parts a merge wraps, or else a new one.
     *
     * @param document the PDF document to process
     */
    @VisibleForTesting
    void fixStructureNamespace(@NotNull PDDocument document) {
        PDStructureTreeRoot root = document.getDocumentCatalog().getStructureTreeRoot();
        if (root == null) {
            return;
        }
        List<COSDictionary> documents = new ArrayList<>();
        for (Object kid : root.getKids()) {
            if (kid instanceof PDStructureElement element && STRUCTURE_TYPE_DOCUMENT.equals(element.getStructureType())) {
                documents.add(element.getCOSObject());
            }
        }
        if (documents.isEmpty() || documents.stream().allMatch(element -> element.containsKey(NS))) {
            return;
        }
        COSBase namespace = findNamespace(documents);
        if (namespace == null) {
            COSDictionary created = new COSDictionary();
            created.setItem(COSName.TYPE, COSName.getPDFName("Namespace"));
            created.setString(NS, PDF_2_NAMESPACE);
            namespace = created;
        }
        for (COSDictionary element : documents) {
            if (!element.containsKey(NS)) {
                element.setItem(NS, namespace);
            }
        }
        COSArray namespaces = root.getCOSObject().getCOSArray(NAMESPACES);
        if (namespaces == null) {
            namespaces = new COSArray();
            root.getCOSObject().setItem(NAMESPACES, namespaces);
        }
        if (!namespaces.toList().contains(namespace)) {
            namespaces.add(namespace);
        }
        logger.debug("Gave the Document element the PDF 2.0 namespace for PDF/UA-2 compliance");
    }

    /** The PDF 2.0 namespace an element at or below the given ones names, or {@code null} where none does. */
    @Nullable
    private COSBase findNamespace(@NotNull List<COSDictionary> elements) {
        Deque<COSDictionary> pending = new ArrayDeque<>(elements);
        Set<COSDictionary> seen = new HashSet<>();
        while (!pending.isEmpty()) {
            COSDictionary element = pending.pop();
            if (!seen.add(element)) {
                continue;
            }
            COSBase namespace = element.getItem(NS);
            COSBase resolved = namespace instanceof COSObject object ? object.getObject() : namespace;
            if (resolved instanceof COSDictionary dictionary && PDF_2_NAMESPACE.equals(dictionary.getString(NS))) {
                return namespace;
            }
            COSBase kids = element.getDictionaryObject(COSName.K);
            if (kids instanceof COSArray array) {
                array.forEach(kid -> addElement(pending, kid));
            } else {
                addElement(pending, kids);
            }
        }
        return null;
    }

    private void addElement(@NotNull Deque<COSDictionary> pending, @Nullable COSBase kid) {
        COSBase resolved = kid instanceof COSObject object ? object.getObject() : kid;
        if (resolved instanceof COSDictionary dictionary && dictionary.containsKey(COSName.S)) {
            pending.push(dictionary);
        }
    }

    /**
     * Fixes XMP metadata according to PDF/UA-2 requirements.
     * <p>
     * According to ISO 14289-2:2024:
     * <ul>
     *     <li>The value of "pdfuaid:rev" shall be the four-digit year (e.g., "2024")</li>
     * </ul>
     *
     * @param document the PDF document to process
     * @throws IOException if an error occurs during metadata processing
     */
    @VisibleForTesting
    void fixXmpMetadata(@NotNull PDDocument document) throws IOException {
        PDMetadata metadata = document.getDocumentCatalog().getMetadata();
        if (metadata == null) {
            logger.warn("No XMP metadata found in document");
            return;
        }

        try {
            // Read current metadata as string
            String metadataString = new String(metadata.toByteArray(), StandardCharsets.UTF_8);

            // Parse and fix XMP metadata using XML DOM
            String fixedMetadata = fixXmpMetadataXml(metadataString);

            if (!fixedMetadata.equals(metadataString)) {
                // Update metadata with fixed version
                metadata.importXMPMetadata(fixedMetadata.getBytes(StandardCharsets.UTF_8));
                logger.info("Updated XMP metadata for PDF/UA-2 compliance");
            } else {
                logger.debug("No XMP metadata changes needed");
            }
        } catch (Exception e) {
            logger.error("Failed to process XMP metadata", e);
            throw new IOException("Failed to process XMP metadata", e);
        }
    }

    /**
     * Fixes XMP metadata XML content according to PDF/UA-2 requirements.
     *
     * @param xmpMetadata the original XMP metadata as XML string
     * @return the fixed XMP metadata as XML string
     * @throws TransformerException if XML transformation fails
     * @throws ParserConfigurationException if XML parser cannot be configured
     * @throws IOException if XML parsing fails
     * @throws SAXException if XML is malformed
     */
    @VisibleForTesting
    String fixXmpMetadataXml(@NotNull String xmpMetadata) throws TransformerException, ParserConfigurationException, IOException, SAXException {
        // Extract the RDF content (between <?xpacket...?> tags)
        String rdfContent = XmpMetadataUtils.extractRdfContent(xmpMetadata);

        // Parse XML
        Document document = XmpMetadataUtils.parseXml(rdfContent);

        // Find all rdf:Description elements
        NodeList descriptions = XmpMetadataUtils.getRdfDescriptions(document);

        boolean metadataModified = false;

        for (int i = 0; i < descriptions.getLength(); i++) {
            Element description = (Element) descriptions.item(i);

            // Check if this is a PDF/UA identification element (has pdfuaid:part attribute)
            String pdfuaidPart = XmpMetadataUtils.getAttributeValue(description, PDFUAID_PART);

            if ("2".equals(pdfuaidPart)) {
                // This is PDF/UA-2 identification - fix it
                metadataModified |= fixPdfUa2Identification(description);
            }
        }

        if (!metadataModified) {
            logger.debug("Not PDF/UA-2 or no metadata changes needed");
            return xmpMetadata;
        }

        // Convert back to string with proper XMP packaging
        String fixedRdf = XmpMetadataUtils.documentToString(document);
        return XmpMetadataUtils.wrapWithXPacket(fixedRdf);
    }

    /**
     * Fixes PDF/UA-2 identification in an rdf:Description element.
     *
     * @param description the rdf:Description element to fix
     * @return true if any changes were made
     */
    @VisibleForTesting
    boolean fixPdfUa2Identification(@NotNull Element description) {
        boolean modified = false;

        // Fix: Add or update pdfuaid:rev to "2024"
        String currentRev = XmpMetadataUtils.getAttributeValue(description, PDFUAID_REV);
        if (currentRev == null || currentRev.isEmpty()) {
            XmpMetadataUtils.setPropertyValue(description, PDFUAID_REV, PDF_UA_2_REV_YEAR);
            logger.debug("Added pdfuaid:rev=\"" + PDF_UA_2_REV_YEAR + "\" to XMP metadata");
            modified = true;
        } else if (!PDF_UA_2_REV_YEAR.equals(currentRev)) {
            XmpMetadataUtils.setPropertyValue(description, PDFUAID_REV, PDF_UA_2_REV_YEAR);
            logger.debug("Updated pdfuaid:rev from \"" + currentRev + "\" to \"" + PDF_UA_2_REV_YEAR + "\"");
            modified = true;
        }

        return modified;
    }
}
