---
name: release-please
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: 🚀 release-please
        id: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445  # v4.2.0
        with:
          release-type: maven
          target-branch: main
